### ISSUE TITLE
yaml parsing

### ISSUE THREAD

**Issue by suzuki-hoge** [suzuki-hoge/has-hub#5]

**Comment by suzuki-hoge** [comment]
```haskell
data FixMe = YamlParseError | NoObjectError
```

**Comment by suzuki-hoge** [comment]
parsing and objecting

**Comment by suzuki-hoge** [comment]
```yaml
# user management

- epic-title  : user management
  epic-number : ?1

# create user

- epic-title  : create user
  epic-number : ?2
  body        : submit user data to post api.
  epics       : [?1]
  milestone   : sprint 1
  pipeline    : sprint backlog

- title       : submit user data
  body        : + [ ] add input elements and submit button
  epics       : [?2]
  milestone   : sprint 1
  labels      : [html, browser]
  pipeline    : sprint backlog

- title       : post api
  body        : + [ ] url dispatch\n+ [ ] write record
  epics       : [?2]
  milestone   : sprint 1
  labels      : [python, database]
  assignees   : [suzuki-hoge]
  pipeline    : sprint backlog

# show users

- epic-title  : show users
  epic-number : ?3
  body        : view all users from get api.
  epics       : [?2]
  milestone   : sprint 2

- title       : get api
  body        : + [ ] url dispatch\n+ [ ] read record
  epics       : [?3]
  milestone   : sprint 2
  labels      : [python, database]
  assignees   : [suzuki-hoge]

- title       : post api
  body        : + [ ] add input elements and submit button
  epics       : [?2]
  milestone   : sprint 2
  labels      : [html, browser]
```

**Comment by suzuki-hoge** [comment]
```yaml
- title: sprint 1
  start_on: 2018/01/01
  due_on: 2018/01/31

- title: sprint 2
  start_on: 2018/02/01
  due_on: 2018/02/28
```
